### ISSUE TITLE
Delete only works on a single character

### ISSUE THREAD

**Issue by mv805** [Uaitt/calculator#1]
When using the delete key, it will only delete a single character. I believe the expected behavior would be to delete a character each time it is pushed.

Also you can enter operators and succesive operators even if there is nothing in the field. Expected behavior would be that you cannot enter operators without a number in the field.

**Comment by Uaitt** [comment]
That's on purpose.

If you look at the script.js file I added a flag on the DEL button that allows to delete only one digit/operator. I have done this because at the moment I was not able to implement an algorithm that made me delete more than one digit.

I believe the correct way would be to store every number inside of a data structure like an array, and when the user deletes the digits I should be able to retrieve the values inside of the array depending how much digits were cancelled. I will surely look at this the next week and see if I can find a solution
